"""remove recorded_at and last_updated from product_details

Revision ID: 707c054ab4b0
Revises: 97555baf4d03
Create Date: 2024-03-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707c054ab4b0'
down_revision: Union[str, None] = '97555baf4d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_details', 'last_updated')
    op.drop_column('product_details', 'recorded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('recorded_at', sa.DateTime(), nullable=False))
    op.add_column('product_details', sa.Column('last_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###
